[WIP]ChatSpaceのDB設計
kouhe0115/chat-space pull request #1
Opened 2019-03-16 10:29 UTC by kouhe0115

DB設計しました
Add users table
Add groups table
Add messages table
Add groups_users table
Add users association
Add groups association
Add messages association
Add groups_users association

2019-03-16 11:24 UTC, kouhe0115 commented
## What
DBのテーブル、カラム、アソシエーションの設計しました

## Why
事前にしっかりと設計をしておかないと、後から変更が難儀なため。
一番基盤の設計であります

2019-03-16 12:08 UTC, yuki-uchida requested changes

2019-03-16 12:08 UTC, yuki-uchida commented on README.md
> +| message_id | int    |          |
idでよいです。また、idは全てのテーブルでデフォルトで実装されるのでなくてよいです

2019-03-16 12:08 UTC, yuki-uchida commented on README.md
> +| user_id  | refference      | not null |
null： falseが正しい書き方です

2019-03-17 02:37 UTC, kouhe0115 commented
レビューありがとうございます。
上記ご指摘箇所、修正しました。
ご確認お願いします。

2019-03-17 06:43 UTC, yuki-uchida requested changes

2019-03-17 06:43 UTC, yuki-uchida commented on README.md
> +| user_id    | int    | null : false |
外部キーの場合にはrefference型にしてforeign_key: trueとする必要があります

2019-03-17 07:10 UTC, kouhe0115 commented
上記指摘点修正しました。
ご確認お願いします。

2019-03-17 07:12 UTC, yuki-uchida commented
LGTMです。お疲れ様でした

2019-03-17 07:14 UTC, kouhe0115 commented
ありがとうございます。

2019-03-17 07:14 UTC, merged